<div class="text-center">
    <h1 class="text-success text-center">Next 3 days forecast</h1>
</div>
<hr>
<div class="container w-75 m-auto border shadow">
    <h2 class="text-start">
        <?php echo $details['location']['name'] ?>
        <span class="h5"><img src="<?php echo $details['current']['condition']['icon']; ?>"></span>
        <span class="text-dark h5"><?php echo $details['current']['condition']['text']; ?></span>
        
    </h2>
    <hr>
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
            <th scope="col">Co</th>
            <th scope="col">No2</th>
            <th scope="col">O3</th>
            <th scope="col">So2</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $details['current']['air_quality']['co'] ?></td>
                <td><?php echo $details['current']['air_quality']['no2'] ?></td>
                <td><?php echo $details['current']['air_quality']['o3'] ?></td>
                <td><?php echo $details['current']['air_quality']['so2'] ?></td>
            </tr>
        </tbody>
    </table>
</div>

