<div class="text-center">
    <h1 class="text-success text-center">Next 3 days forecast</h1>
</div>
<hr>
<div class="container w-75 m-auto border shadow">
    <h2 class="text-start">
        <?php echo $details['location']['name'] ?>
        <span class="h5"><img src="<?php echo $details['current']['condition']['icon']; ?>"></span>
        <span class="text-dark h5"><?php echo $details['current']['condition']['text']; ?></span>
        
    </h2>
    <hr>
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
            <th scope="col">Date</th>
            <th scope="col">Condition</th>
            <th scope="col">Sunrise</th>
            <th scope="col">Sunset</th>
            <th scope="col">Max Temp</th>
            <th scope="col">Min Temp</th>
            <th scope="col">Avg Temp</th>
            <th scope="col">Wind</th>
            <th scope="col">Humidity</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach($details['forecast']['forecastday'] as $day) {
                echo'<tr>
                        <th scope="row">'.$day['date'].'</th>
                        <td><img src="'.$day['day']['condition']['icon'].'"><br><small>'.$day['day']['condition']['text'].'</small></td>
                        <td>'.$day['astro']['sunrise'].'</td>
                        <td>'.$day['astro']['sunset'].'</td>
                        <td>'.$day['day']['maxtemp_c'].'°C</td>
                        <td>'.$day['day']['mintemp_c'].'°C</td>
                        <td>'.$day['day']['avgtemp_c'].'°C</td>
                        <td>'.$day['day']['maxwind_kph'].' Km/H</td>
                        <td>'.$day['day']['avghumidity'].'%</td>
                    </tr>';
            }
            ?>
        </tbody>
    </table>
</div>

