<div class="text-center">
    <h1 class="text-success text-center">Sports events</h1>
</div>
<hr>
<div class="container w-75 m-auto border shadow">
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
            <th scope="col">Sport</th>
            <th scope="col">Country</th>
            <th scope="col">Stadium</th>
            <th scope="col">Tournament</th>
            <th scope="col">Start</th>
            <th scope="col">Match</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach($details['football'] as $day) {
                echo'<tr>
                        <th scope="row">Football</th>
                        <td>'.$day['country'].'</td>
                        <td>'.$day['stadium'].'</td>
                        <td>'.$day['tournament'].'</td>
                        <td>'.$day['start'].'</td>
                        <td>'.$day['match'].'</td>
                    </tr>';
            }
            ?>
        </tbody>
    </table>
</div>

