<div class="text-center">
    <h1 class="text-success text-center">Sports events</h1>
</div>
<hr>
<div class="container w-75 m-auto border shadow">
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
            <th scope="col">Sport</th>
            <th scope="col">Country</th>
            <th scope="col">Stadium</th>
            <th scope="col">Tournament</th>
            <th scope="col">Start</th>
            <th scope="col">Match</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach($details as $key=>$val) {
                foreach ($val as $v) {
                    echo'<tr>
                        <th scope="row">'.$key.'</th>
                        <td>'.$v['country'].'</td>
                        <td>'.$v['stadium'].'</td>
                        <td>'.$v['tournament'].'</td>
                        <td>'.$v['match'].'</td>
                        <td>'.$v['start'].'</td>
                    </tr>';
                }
                
            }
            ?>
        </tbody>
    </table>
</div>

