<div class="text-center">
    <h1 class="text-success text-center">Details</h1>
</div>
<hr>
<div class="container w-50 m-auto border shadow">
    <h2 class="text-start">
        <?php echo $details['location']['name'] ?>
    </h2>
    <hr>
    <p>
        <span class="text-danger h5">Timezone-</span>
        <span class="mx-2">TZ: &nbsp<?php echo $details['location']['tz_id'] ?> </span>
        <span class="mx-2">Local Time: &nbsp<?php echo $details['location']['localtime'] ?> </span>
    </p>
</div>
<?php
// echo'<pre>';
// print_r($details);


