<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Weather-App</title>
    <link rel="stylesheet" href="/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
    </style>
</head>

<body>
    <div class="container-fluid">
        <?php echo $this->getContent(); ?>
    </div>
    <script src="/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>